global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
      monitor: prom

rule_files:
  - /etc/prometheus/alerts/*.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']


  - job_name: 'node discovery'
    file_sd_configs:
    - files:
      - 'targets.yml'
